name: Daily Internship Scraper

on:
  schedule:
    - cron: '0 3 * * *' # 3 AM UTC = 9 AM IST
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper
        env:
          YOUR_EMAIL: ${{ secrets.YOUR_EMAIL }}
          YOUR_APP_PASSWORD: ${{ secrets.YOUR_APP_PASSWORD }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: python main.py
