name: Daily Internship Scraper

on:
  schedule:
    - cron: '5 9 * * *'  # 14:35 IST (09:05 UTC)
  workflow_dispatch:


jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # Install core packages first
          pip install beautifulsoup4==4.12.2
          pip install requests==2.31.0
          pip install lxml==4.9.3
          
          # Try different LinkedIn scraping packages
          pip install linkedin-scraper || pip install linkedin-jobs-scraper || echo "LinkedIn package installation failed, continuing..."
          
      - name: Run scraper
        env:
          YOUR_EMAIL: ${{ secrets.YOUR_EMAIL }}
          YOUR_APP_PASSWORD: ${{ secrets.YOUR_APP_PASSWORD }}
          RECEIVERS: ${{ secrets.RECEIVERS }}
        run: python main.py
